export const ADD_TO_CART='ADD_TO_CART';
export const REMOVE_FROM_CART='REMOVE_FROM_CART';
export const EMPTY_CART='EMPTY_CART';
export const PROLIST_SELECTED='PROLIST_SELECTED';
export const SEARCH_ITEM='SEARCH_ITEM';